### ISSUE TITLE
wrong-type-argument consp nil in wc-create

### ISSUE THREAD

**Issue by dgutov** [ilohmar/wconf#1]
I just wanted to try it out, copied the source of the package into scratch, and evaluated it. As such, I have no file called `window-configs.el`, nor have I added anything to global hooks.

Try this:

- `M-x wc-switch-to-config` => `Wrong type argument: consp, nil`
- `M-x wc-create` => same error

**Comment by ilohmar** [comment]
This should be fixed with the proper `interactive` forms.  The examples work for me in a plain emacs -q now.  Switching w/o configs can still result in an error, will make this more obvious.

**Comment by ilohmar** [comment]
Reopening this, as there is still work to do to make errors and messages helpful/robust.

**Comment by ilohmar** [comment]
The interactive functions should now be more reasonable (proper messages and more robust behavior).  Closing this for now --- feel free to re-open when related problems persist/re-occur.

**Comment by dgutov** [comment]
Thank you.
